/**
 * commands.js
 *
 * Defines the bot’s command registry.
 *
 * Flow:
 *   bot.js parses a message into { cmd, rest } and calls:
 *     registry.get(cmd)?.({ message, cmd, rest })
 *
 * Adding a new command:
 *   1) Register it in the appropriate module:
 *        register("!mycmd", async ({ message, rest }) => { ... }, "!mycmd — help text");
 *   2) Parse `rest` (trim / split on /\s+/) and validate inputs.
 *   3) Reply with `message.reply(...)` or `message.channel.send(...)`.
 *
 * Notes:
 *   - Unknown commands are ignored.
 *   - Admin-only commands: pass { admin: true } and enforce permission in handler.
 *   - `!help` is autogenerated from registry help strings and hides admin commands.
 */

import { registerContests } from "./contests.js";
import { registerTrades } from "./trades.js";
import { registerRarity, registerLevel4Rarity } from "./rarity.js";
import { registerGames } from "./games/games.js";

import { registerInfoCommands } from "./faq.js";
import { registerTools } from "./tools.js";
import { registerToybox } from "./toybox.js";

/* --------------------------------- config -------------------------------- */

// These are used only to decide whether to register commands at all.
// Enforcement should still happen inside the respective modules too (you already do this for rarity/trading).
const TRADING_GUILD_ALLOWLIST = (process.env.TRADING_GUILD_ALLOWLIST || "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const RARITY_GUILD_ALLOWLIST = (process.env.RARITY_GUILD_ALLOWLIST || "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const TRADING_ENABLED_ANYWHERE = TRADING_GUILD_ALLOWLIST.length > 0;
const RARITY_ENABLED_ANYWHERE = RARITY_GUILD_ALLOWLIST.length > 0;

/* -------------------------------- registry -------------------------------- */

export function buildCommandRegistry() {
  const registry = new Map();

  // Helper to register commands
  function register(name, handler, help = "", opts = {}) {
    const entry = {
      handler,
      help,
      admin: Boolean(opts.admin),
      canonical: true
    };

    registry.set(name.toLowerCase(), entry);

    // Register aliases (if any)
    if (Array.isArray(opts.aliases)) {
      for (const alias of opts.aliases) {
        registry.set(alias.toLowerCase(), {
          ...entry,
          canonical: false
        });
      }
    }
  }

  /* ------------------------------ Module wiring ------------------------------ */

  // Core / fun / contests (also contains: ?roll, ?choose, ?elim, !coinflip, !awesome per your refactor)
  registerContests(register);

  // FAQ / Wiki / NG / Rules / Glossary (moved into faq.js)
  registerInfoCommands(register);

  // Tools hub + organizer link + calculator (!calc) (collated in tools.js)
  registerTools(register);

  // Toybox fun commands (e.g. !rig)
  registerToybox(register);

  // Trading lists + IDs (?ft/?lf/?id etc.) behind allowlist
  if (TRADING_ENABLED_ANYWHERE) {
    registerTrades(register);
  }

  // Rarity commands behind allowlist (but L4 is available everywhere)
  if (RARITY_ENABLED_ANYWHERE) {
    registerRarity(register);
  }
  registerLevel4Rarity(register);

  // Games registry (exploding voltorbs etc.)
  registerGames(register);

  /* ------------------------------ Local commands ----------------------------- */

  register(
    "!help",
    async ({ message }) => {
      const lines = [];

      for (const { help, admin, canonical } of registry.values()) {
        if (!canonical) continue; // hide aliases
        if (!help) continue;
        if (admin) continue; // hide admin commands
        lines.push(help);
      }

      if (lines.length === 0) return;

      await message.reply(
        "**Available commands:**\n" + lines.sort().map((l) => `• ${l}`).join("\n")
      );
    },
    "!help — shows this help message",
    { aliases: ["!helpme"] }
  );

  /* ------------------------------ Public API ----------------------------- */

  return {
    get: (name) => registry.get(String(name).toLowerCase())?.handler,
    list: () => [...registry.keys()].sort()
  };
}
