/**
 * commands.js
 *
 * Defines the bot’s command registry.
 *
 * Flow:
 *   bot.js parses a message into { cmd, rest } and calls:
 *     registry.get(cmd)?.({ message, cmd, rest })
 *
 * Adding a new command:
 *   1) Register it in the appropriate module:
 *        register("!mycmd", async ({ message, rest }) => { ... }, "!mycmd — help text");
 *   2) Parse `rest` (trim / split on /\s+/) and validate inputs.
 *   3) Reply with `message.reply(...)` or `message.channel.send(...)`.
 *
 * Notes:
 *   - Unknown commands are ignored.
 *   - Admin-only commands: pass { admin: true } and enforce permission in handler.
 *   - `!help` is autogenerated from registry help strings and hides admin commands.
 */

import { registerContests } from "./contests.js";
import { registerTrades } from "./trades.js";
import { registerGames } from "./games/games.js";

import { registerInfoCommands } from "./faq.js";
import { registerTools } from "./tools.js";
import { registerToybox } from "./toybox.js";

/* --------------------------------- config -------------------------------- */

// These are used only to decide whether to register commands at all.
// Enforcement should still happen inside the respective modules too (you already do this for rarity/trading).
const TRADING_GUILD_ALLOWLIST = (process.env.TRADING_GUILD_ALLOWLIST || "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);


const TRADING_ENABLED_ANYWHERE = TRADING_GUILD_ALLOWLIST.length > 0;

/* -------------------------------- registry -------------------------------- */

export function buildCommandRegistry() {
  const registry = new Map();

  // Helper to register commands
  function register(name, handler, help = "", opts = {}) {
    const entry = {
      handler,
      help,
      admin: Boolean(opts.admin),
      canonical: true,
      category: opts.category || "Other"
    };

    registry.set(name.toLowerCase(), entry);

    if (Array.isArray(opts.aliases)) {
      for (const alias of opts.aliases) {
        registry.set(alias.toLowerCase(), {
          ...entry,
          canonical: false
        });
      }
    }
  }

  function withCategory(baseRegister, category) {
    return (name, handler, help = "", opts = {}) => {
      // Allow per-command override if you ever want it
      const merged = { ...opts };
      if (!merged.category) merged.category = category;
      return baseRegister(name, handler, help, merged);
    };
  }

  function helpModel() {
    const byCat = new Map();
    const catOrder = [];

    for (const { help, admin, canonical, category } of registry.values()) {
      if (!canonical) continue;
      if (!help) continue;
      if (admin) continue;

      const cat = category || "Other";
      if (!byCat.has(cat)) {
        byCat.set(cat, []);
        catOrder.push(cat);
      }
      byCat.get(cat).push(help);
    }

    return catOrder.map((cat) => ({
      category: cat,
      lines: (byCat.get(cat) || []).sort()
    }));
  }

  /* ------------------------------ Module wiring ------------------------------ */

  // Trading lists + IDs (?ft/?lf/?id etc.) behind allowlist
  if (TRADING_ENABLED_ANYWHERE) {
    registerTrades(withCategory(register, "Trading"));
  }

  // Tools hub + organizer link + calculator (!calc) (collated in tools.js)
  registerTools(withCategory(register, "Tools"));

  // FAQ / Wiki / NG / Rules / Glossary (moved into faq.js)
  registerInfoCommands(withCategory(register, "Info"));

  // Core / fun / contests (also contains: ?roll, ?choose, ?elim, !coinflip, !awesome per your refactor)
  registerContests(withCategory(register, "Contests"));

  // Games registry (exploding voltorbs etc.)
  registerGames(withCategory(register, "Games"));

  // Toybox fun commands (e.g. !rig)
  registerToybox(withCategory(register, "Fun"));

  /* ------------------------------ Local commands ----------------------------- */

  register("!help", async ({ message }) => {
    const pages = helpModel();
    if (!pages.length) return;

    const sections = pages.map(
      (p) =>
        `**${p.category}**\n` +
        p.lines.map((l) => `• ${l}`).join("\n")
    );

    await message.reply(sections.join("\n\n"));
  }, "!help — shows this help message", { aliases: ["!helpme"], category: "Info" });

  /* ------------------------------ Public API ----------------------------- */

  return {
    get: (name) => registry.get(String(name).toLowerCase())?.handler,
    list: () => [...registry.keys()].sort(),
    helpModel
  };
}
